export interface IContractInfo {
    contractid: number,
    totalprice_r: number,
    totalprice_fc: number,
    projectManager: string,
    projectManagerImage: string,
    customer: string,
    currency: string,
    startoperationdate: Date,
    notificationdate: Date,
    planstartdate: Date,
    finishdate: Date,
    duration: number,
    passedDuration: number,
    addendumDuration: number,
    // startOperationShamsiDate: string,
    // notificationShamsiDate: string,
    // finishShamsiDate: string,
    // planStartShamsiDate: string,
    // attachmentcontractprice1_r: number,
    // attachmentcontractprice1_fc: number,
    // attachmentcontractprice2_r: number,
    // attachmentcontractprice2_fc: number,
    // attachmentcontractprice3_r: number,
    // attachmentcontractprice3_fc: number,
    // attachmentcontractprice4_r: number,
    // attachmentcontractprice4_fc: number,
    // attachmentcontractprice5_r: number,
    // attachmentcontractprice5_fc: number,
}

export interface IContractInfoRequest {
    contractid: number,
    startoperationdate: string,
    notificationdate: string,
    planstartdate: string,
    finishdate: string,
    // attachmentcontractprice1_r: number,
    // attachmentcontractprice1_fc: number,
    // attachmentcontractprice2_r: number,
    // attachmentcontractprice2_fc: number,
    // attachmentcontractprice3_r: number,
    // attachmentcontractprice3_fc: number,
    // attachmentcontractprice4_r: number,
    // attachmentcontractprice4_fc: number,
    // attachmentcontractprice5_r: number,
    // attachmentcontractprice5_fc: number,
}