export interface IProgressState {
    progressstateid: number,
    contractid: number,
    dateid: number,
    year: string,
    month: string,
    plan_replan: string,
    pp_e: number,
    ap_e: number,
    pp_p: number,
    ap_p: number,
    pp_c: number,
    ap_c: number,
    pp_t: number,
    ap_t: number,
    pr_t: number,
    pfc_t: number,
    description: string,
}

export interface IRequestProgressState {
    contractid: number,
    dateid: number,
    plan_replan: string,
    pp_e: number,
    ap_e: number,
    pp_p: number,
    ap_p: number,
    pp_c: number,
    ap_c: number,
    pp_t: number,
    ap_t: number,
    pr_t: number,
    pfc_t: number,
    description: string,
}